### ISSUE TITLE
spritemap.svg as manifest key

### ISSUE THREAD

**Issue by portfolioris** [SpiriitLabs/vite-plugin-svg-spritemap#14]
Would it be possible to remove the hash from the Vite manifest key output, so like this:

Instead of
```
  "spritemap.2ffa3d27.svg": {
    "file": "assets/spritemap.2ffa3d27.svg",
    "src": "spritemap.2ffa3d27.svg"
  },
```

to
```
  "spritemap.svg": {
    "file": "assets/spritemap.2ffa3d27.svg",
    "src": "spritemap.2ffa3d27.svg"
  },
```

Or anything similiar?

**Comment by Applelo** [comment]
Currently, it's not possible but I can check to make this customizable inside the options.

**Comment by Applelo** [comment]
This will be a breaking change but it's a better way to doing things. The emitted file will be handle by rollup via the [options.output.filename](https://rollupjs.org/configuration-options/#output-assetfilenames) option.

**Comment by jonleverrier** [comment]
+1 - this would be amazing

**Comment by portfolioris** [comment]
@Applelo I'm using Node 18, LTS.

**Comment by IanIsFluent** [comment]
I'm trying to integrate with AspNetCore using https://github.com/Eptagone/Vite.AspNetCore, and I'm not sure how to get the name of the file with the hash, considering the manifest doesn't store the mapping from spritemap.svg -> spritemap.565041bf.svg.

Am I missing something obvious?

**Comment by Applelo** [comment]
No this is a current issue I am resolving currently. With the 1.4.0 you will can set the key inside the `manifest.json` by providing a `name` inside the output object.
The release is almost ready, need to add proper test and typing :)

**Comment by IanIsFluent** [comment]
> No this is a current issue I am resolving currently. With the 1.4.0 you will can set the key inside the `manifest.json` by providing a `name` inside the output object. The release is almost ready, need to add proper test and typing :)

Wow that was a quick reply, thanks!

I can set the filename to static - but of course, then I wouldn't get the cache-busting...

1. set a static filename in the `vite.config.ts`:
```VitePluginSvgSpritemap('./Assets/icons/*.svg', {
  output: {
    filename: 'spritemap.svg',
```
    
2. switch between that static filename and the `__spritemap` href using `<environment` elements from AspNetCore:
```
  <environment include="Development">
    <use href="__spritemap#sprite-icon-name"></use>
  </environment>
  <environment include="">
    <use href="spritemap.svg#sprite-icon-name"></use>
  </environment>
```

**Comment by Applelo** [comment]
The version 1.4.0 is out know and you can set the name property. Reopen the issue if you have still the problem.

**Comment by jonleverrier** [comment]
Working great!

**Comment by IanIsFluent** [comment]
This is great, thank you! For future reference, getting this working with Vite.AspNetCore involved adding a helper function to return `__spritemap` or `Manifest["spritemap.svg"]?.File` depending on dev or prod:

```
if (Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") == Environments.Development)
{
    return $"__spritemap#sprite-{spriteName}";
}
else
{ 
    // assume production
    return $"{Manifest["spritemap.svg"]?.File}#sprite-{spriteName}";
}
```
