### ISSUE TITLE
Paths to the SVG sprite via SCSS return 404

### ISSUE THREAD

**Issue by jonleverrier** [SpiriitLabs/vite-plugin-svg-spritemap#20]
Firstly, thanks for this plugin! Secondly, you'll have to forgive this ramble, as I'm new to `vitejs`.

I'm using `vitejs` as a development environment, but mainly to compile my javascript and sass. I'm using Craft CMS as a backend, so all assets export to a `dist` folder, and Craft CMS picks them up from there [via a plugin](https://github.com/nystudio107/craft-vite).

I'm using your [SASS](https://github.com/SpiriitLabs/vite-plugin-svg-spritemap/blob/main/demo/basic/src/scss/spritemap.scss) mixin to load an icon from my sprite file into my sass like so:

```
@use '../mixins' as *;

h1 {
    &:before {
        content: '';
        display: inline-block;
        @include sprite(
            $name: icon-example, 
            $include-size: box, 
            $type: fragment
        );
    }   
}
```
When my CSS is generated for production this works great, apart from the path to assets are wrong and I get a note in the console.

**Note in console:**
```/__spritemap#sprite-icon-example-view in /var/www/html/build/scss/app.scss didn't resolve at build time, it will remain unchanged to be resolved at runtime```

**Actual path to sprite in generated CSS:**
`https://vite.local.ddev.site/assets/spritemap.1242586e.svg#sprite-icon-example-view`

**Expected path to sprite:**
`https://vite.local.ddev.site/dist/assets/spritemap.1242586e.svg#sprite-icon-example-view`

When the vite dev server is running, it returns the following path which returns a 404:
`https://vite.local.ddev.site/__spritemap__1242586e.svg#sprite-icon-example-view`

Here's a cut down version of my vite.config.js:

```
import {defineConfig} from 'vite';
import path from 'path';
import VitePluginSvgSpritemap from '@spiriit/vite-plugin-svg-spritemap';

export default defineConfig(({command}) => ({
    base: command === 'serve' ? '' : '/dist/',
    publicDir: path.resolve(__dirname, './build/static'),
    build: {
        emptyOutDir: true,
        manifest: true,
        outDir: path.resolve('./public/dist'),
        sourcemap: true,
        rollupOptions: {
            input: {
                // scss imported via my js
                'js/app': './build/js/app.js',
              },
            output: {
                entryFileNames: '[name].[hash].js',
                chunkFileNames: '[name].[hash].js',
                assetFileNames: '[ext]/[name].[hash].[ext]',
            }
        },
    },
    plugins: [
        VitePluginSvgSpritemap('./build/icons/*.svg', {
            prefix: 'sprite-',
            output: {
                filename: '[name].[hash].[ext]',
              },
            styles: {
                lang: 'scss',
                filename: 'build/scss/mixins/_sprite.scss',
            }
        }),
    ],
}));
```

Any help appreciated.

**Comment by Applelo** [comment]
Hello, for the note in the console I didn't find a fix yet. It doesn't cause a bug, it's just a warning from ViteJS. 

In development with a backend, you need to manage the url manually because vitejs doesn't rewrite your HTML.
For example :
https://github.com/SpiriitLabs/vite-plugin-svg-spritemap/blob/a215dc79b7685bd47c89c0f6614eeceb1ec63341/demo/server/index.html#L32
I will update the readme to be more clear about this.

**Comment by jonleverrier** [comment]
> Hello, for the note in the console I didn't find a fix yet. It doesn't cause a bug, it's just a warning from ViteJS.

No problem!

> In development with a backend, you need to manage the url manually because vitejs doesn't rewrite your HTML.

I read about this. My backend is simply loading the compiled CSS, so won't have the ability to rewrite any URLS within the CSS.

As I'm using your SASS mixin, I don't have any control over the URL either, which leaves me with 2 options:

1. Re-write your SASS mixin
2. Use PostCSS to rewrite the URLs on build

I think the underlying problem is: your plugin doesn't seem to respect vite js `build.outDir` setting.

**Comment by Applelo** [comment]
Oh ok, I didn't test the fragment option in the mixin with this context and It will not work. I need to check if I can make it work for this context. You can use the default option using base64 url `@include sprite($name);`.

**Comment by jonleverrier** [comment]
Hi @Applelo - I'm going to close this issue as I have found a work around for using your SASS mixin in dev/build modes for my use case.

If anybody else stumbles across this post, this might help you. I have the following in my vite.config.js file:

```
css: {
    preprocessorOptions: {
        scss: { 
            // conditionally set SASS $sprite-type value
            additionalData:  command === 'serve' ? `@use 'build/scss/theme/setup' with ($sprite-type: uri);` : `@use 'build/scss/theme/setup' with ($sprite-type: fragment);`,
        },
    },
},
```

And use the mixin like so:

```
@use '../mixins' as *;
@use '../theme' as *;

h1 {
    &:before {
        content: '';
        display: inline-block;
        @include sprite(
            $name: icon-example, 
            $include-size: box, 
            $type: $sprite-type
        );
    }   
}
```

Now in `dev`, the sprite mixin will base64 the url (type uri). In `production` the url will be given to the sprite file (type fragment).
