### ISSUE TITLE
Is there anyway for the SASS mixin to respect build.outDir path?

### ISSUE THREAD

**Issue by jonleverrier** [SpiriitLabs/vite-plugin-svg-spritemap#21]
Great work on the plugin!

When I use the SASS mix here with `type: fragment`:
https://github.com/SpiriitLabs/vite-plugin-svg-spritemap/blob/a215dc79b7685bd47c89c0f6614eeceb1ec63341/demo/basic/src/scss/spritemap.scss#L17

When building for production, It will reference a path to the sprite file from my CSS like so:
`/assets/spritemap.63529215.svg`

When it should be
`/dist/assets/spritemap.63529215.svg`

As I have the following set in my vite.config.js:
```
build: {
    outDir: path.resolve('./public/dist'),
    ...
```

I've fixed this using a PostCSS plugin, but it would be great to fix this behaviour natively even if it meant adding a 5th parameter to the SASS mixin!

**Comment by Applelo** [comment]
Yes, it should be fix in the version 2.0 because the plugin doesn't use rollup to output in the assetsDirectory.

**Comment by jonleverrier** [comment]
Note the 5th parameter. Set to blank so not to cause breaking changes.

```
@mixin sprite($name, $include-size: false, $type: 'uri', $mode: 'background', $outDir: '') {
  $sprite: map-get($sprites, $name);
  $url: false;

  @if $type == 'fragment' {
    $url: '#{outDir}/__spritemap##{$sprites-prefix}#{$name}-view';
  } @else if $type == 'uri' {
    $url: map-get($sprite, uri);
  } @else {
    @error 'sprite(): $type must be either "fragment" or "uri"';
  }

  @if $url {
    #{$mode}: url($url) center no-repeat;

    @if $include-size {
      @if $include-size == true {
        #{$mode}-size: map-get($sprite, width) map-get($sprite, height);
      } @else if $include-size == 'box' {
        width: map-get($sprite, width);
        height: map-get($sprite, height);
      }
    }
  }
}
```

**Comment by jonleverrier** [comment]
> Yes, it should be fix in the version 2.0 because the plugin doesn't use rollup to output in the assetsDirectory.

Great news. Do you have any ideas when v2 _might_ be released?

**Comment by Applelo** [comment]
No idea, this is a project I maintain in my work time in my company. I hope in the current month.

**Comment by Applelo** [comment]
I have fix it in the 1.4.0 (should come very soon). However, outDir don't seem to be the right option for the path adjust and should be the [base option](https://vitejs.dev/config/shared-options.html#base). Tell me if you are ok with this change.

**Comment by jonleverrier** [comment]
Thanks for checking @Applelo. I think this should be fine.

This is a shortened config I'm using - so all looks good:

```
export default defineConfig(({command}) => ({
    base: command === 'serve' ? '' : '/dist/',
    ...
    build: {
        emptyOutDir: true,
        outDir: path.resolve('./public/dist'),
        ...
```

**Comment by Applelo** [comment]
The version 1.4.0 is out know, it should support the base option. Reopen the issue if you have still the problem.

**Comment by jonleverrier** [comment]
All working great. Thanks @Applelo
