### ISSUE TITLE
Add support of Vite 5

### ISSUE THREAD

**Issue by TiroZit** [SpiriitLabs/vite-plugin-svg-spritemap#25]
Warnings on dev mode: 
`plugin 'vite-plugin-svg-spritemap:dev' uses deprecated 'enforce' option. Use 'order' option instead.`
`plugin 'vite-plugin-svg-spritemap:dev' uses deprecated 'transform' option. Use 'handler' option instead.`
![image](https://github.com/SpiriitLabs/vite-plugin-svg-spritemap/assets/78494774/036ea3b6-cfe6-4217-83f9-7dfdad50b97d)

**Comment by Applelo** [comment]
Thanks for the report. This is just deprecation warning and an easy fix to implement. This fix will be implemented in the 2.0.0 and so, the plugin will drop the support of Vite 3.

Related to #24
