### ISSUE TITLE
Support for multiple instance

### ISSUE THREAD

**Issue by Applelo** [SpiriitLabs/vite-plugin-svg-spritemap#39]
Currently, multiple instance of the plugin are not possible because of the __spritemap server. 
Make `/__spritemap` editable by the user with the `output.name` option ? 

```ts
{

plugins: [
      VitePluginSvgSpritemap('./assets/icons/*.svg', {
        output: {
          filename: '[name].[hash][extname]',
          view: false,
        },
      }),
      VitePluginSvgSpritemap('./assets/flags/*.svg', {
        output: {
          filename: 'flags.[hash][extname]',
          view: false,
        },
      }),
    ],
}
```

**Comment by shurco** [comment]
> Currently, multiple instance of the plugin are not possible because of the __spritemap server. Make `/__spritemap` editable by the user with the `output.name` option ?
> 
> ```ts
> {
> 
> plugins: [
>       VitePluginSvgSpritemap('./assets/icons/*.svg', {
>         output: {
>           filename: '[name].[hash][extname]',
>           view: false,
>         },
>       }),
>       VitePluginSvgSpritemap('./assets/flags/*.svg', {
>         output: {
>           filename: 'flags.[hash][extname]',
>           view: false,
>         },
>       }),
>     ],
> }
> ```

try this way :

```ts
{
  plugins: [
    VitePluginSvgSpritemap([
      "./assets/icons/*.svg",
      "./assets/flags/*.svg",
    ], {
      output: {
        view: false,
      },
    }),
  ]
}
```

**Comment by Applelo** [comment]
Yeah I know, but I want to generate two spritemap, one for my icons, and one for the flags :)

**Comment by hybrid897** [comment]
@Applelo I have a similar scenario except with a set of map icons that I would like in a different spritemap. Is there an issue blocking the current PR you have raised? Thank you for the plugin :)

**Comment by Applelo** [comment]
The current PR is blocked because of lack of time on my part. I wish to make an update at the end of this month 🤞

**Comment by liushuog** [comment]
May I ask when version 2.3.0 can be released?

**Comment by Applelo** [comment]
The last time I give an estimate time, I was completely wrong. So what I can say: I am working on it every week. I need to finish the styles callback and add testing for all the new features 😅
7 months since no release is not what I was hoping for this plugin 🫤 

For the next version, I hope to do more little release and fix all the bugs fixes reported by everyone (and enforce proper reproduction on issues 🥹).
