### ISSUE TITLE
Incorrect spritemap.svg path got when build on Windows.

### ISSUE THREAD

**Issue by 0xDarker** [SpiriitLabs/vite-plugin-svg-spritemap#45]
I got **"/assetsspritemap.[hash].svg"** when build with Vite on Windows.
But on Linux, it works fine.

**Comment by Applelo** [comment]
Hi, can you share a reproduction? I have tried on my windows machine, there is a small problem with the type of slash but not this kind of error.

**Comment by 0xDarker** [comment]
> Hi, can you share a reproduction? I have tried on my windows machine, there is a small problem with the type of slash but not this kind of weird path.

Here is the reproduction project.
[demo.zip](https://github.com/SpiriitLabs/vite-plugin-svg-spritemap/files/13998079/demo.zip)

**Comment by 0xDarker** [comment]
https://github.com/SpiriitLabs/vite-plugin-svg-spritemap/blob/669f31ffc4bee03f47876c0bd0574ac5d443aaa8/src/plugins/build.ts#L62

maybe use `path.posix.join` ?

**Comment by Applelo** [comment]
Hi, I have already implemented on my branch and this is not the problem. It is related to Vue plugin and windows some how. I continue to investigate.

**Comment by Applelo** [comment]
So you was right, all path in build need to use posix format. A fix is coming in the 2.2.4.
